security:
  jwt:
    secret-key: 406a970f5fdd329ef30bb1b0e6205f7692d69647322a926bd30ac84ab1c6b8fa
    expiration-time: 3600000

spring:
  application:
    name: advanced-software

  datasource:
    url: jdbc:postgresql://pg-swe-ahmedosamaft-b177.j.aivencloud.com:17641/lms?ssl=require&user=avnadmin&password=AVNS_eqCAEXHlcDKjgmeC8lL
    username: avnadmin
    password: AVNS_eqCAEXHlcDKjgmeC8lL
    driver-class-name: org.postgresql.Driver

  jpa:
    #    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
#logging:
#  level:
#    org:
#      springframework:
#        security: trace
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace
#        SQL: DEBUG
#        type.descriptor.sql.BasicBinder: trace
server:
  port: 9090