security:
  jwt:
    secret-key: 406a970f5fdd329ef30bb1b0e6205f7692d69647322a926bd30ac84ab1c6b8fa
    expiration-time: 3600000

spring:
  profiles:
    active: db-docker

  application:
    name: advanced-software

  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: validate

    properties:
      hibernate:
        format_sql: true
logging:
  level:
    "fci.swe.advanced_software": trace
#    org:
#      hibernate:
#        orm:
#          jdbc:
#            bind: trace
#        SQL: DEBUG
#        type.descriptor.sql.BasicBinder: trace

server:
  port: 9090
